import { EInputType, TFormField } from "../types/formField";
import { z } from "zod";

export const registerFormSchema = z.object({
  name: z
    .string({ required_error: "enter your firstname" })
    .min(4, { message: "firstname should not be less than 4 words" }),
  email: z.string().email({ message: "please enter valid email" }),
  password: z
    .string()
    .min(8, { message: "password should not be less than 8 words" }),
  role: z.string(),
  dob: z.string().regex(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/),
  phone: z.string().regex(/^[0-9]{10}$/),
  paddress: z.string({ required_error: "enter your permanent address" }),
  taddress: z.string({ required_error: "enter your temporary address" }),
  bloodGroup: z.string(),
  religion: z.string(),
  motherTongue: z.string(),
  admissionNo: z.string(),
  regdNo: z.string(),
  academicYear: z.string(),
  joiningDate: z.string().regex(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/),
  expectedPassoutDate: z.string().regex(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/),
  studentType: z.string(),
  rollNo: z.string(),
  libraryId: z.string(),
  panNo: z.string(),
  staffId: z.string(),
  staffType: z.string(),
  licenseNo: z.string(),
  citizenshipId: z.string(),
  designation: z.string(),
  payrollType: z.string(),
});

export type TRegisterFormSchema = z.infer<typeof registerFormSchema>;
export const registerFormDefaultValue: Partial<TRegisterFormSchema> = {
  name: "adarsh",
  email: "a@gmail.com",
  password: "adadadsfasdfa",
  role: "ads",
  dob: "2024-12-18",
  phone: "1231231231",
  paddress: "sdf",
  taddress: "adsf",
  bloodGroup: "ad",
  religion: "adf",
  motherTongue: "adf",
  admissionNo: "adf",
  regdNo: "adf",
  academicYear: "adsf",
  joiningDate: "0021-02-11",
  expectedPassoutDate: "0012-12-21",
  studentType: "12",
  rollNo: "12",
  libraryId: "12",
  panNo: "12",
  staffId: "1221",
  staffType: "12",
  licenseNo: "12",
  citizenshipId: "12",
  designation: "21",
  payrollType: "21",
};

export const registerFormField: TFormField<TRegisterFormSchema>[] = [
  {
    label: "Name",
    name: "name",
    type: EInputType.TEXT,
    placeholder: "Enter your name",
    required: true,
  },
  {
    label: "Email",
    name: "email",
    type: EInputType.EMAIL,
    placeholder: "Enter your email",
    required: true,
  },
  {
    label: "Password",
    name: "password",
    type: EInputType.PASSWORD,
    placeholder: "Enter your password",
    required: true,
  },
  {
    label: "Role",
    name: "role",
    type: EInputType.TEXT,
    placeholder: "Enter your role",
    required: true,
  },
  {
    label: "Date of Birth",
    name: "dob",
    type: EInputType.DATE,
    placeholder: "YYYY-MM-DD",
    required: true,
  },
  {
    label: "Phone",
    name: "phone",
    type: EInputType.TEL,
    placeholder: "Enter your phone number",
    required: true,
  },
  {
    label: "Permanent Address",
    name: "paddress",
    type: EInputType.TEXT,
    placeholder: "Enter your permanent address",
    required: true,
  },
  {
    label: "Temporary Address",
    name: "taddress",
    type: EInputType.TEXT,
    placeholder: "Enter your temporary address",
    required: true,
  },
  {
    label: "Blood Group",
    name: "bloodGroup",
    type: EInputType.TEXT,
    placeholder: "Enter your blood group",
    required: false,
  },
  {
    label: "Religion",
    name: "religion",
    type: EInputType.TEXT,
    placeholder: "Enter your religion",
    required: false,
  },
  {
    label: "Mother Tongue",
    name: "motherTongue",
    type: EInputType.TEXT,
    placeholder: "Enter your mother tongue",
    required: false,
  },
  {
    label: "Admission No",
    name: "admissionNo",
    type: EInputType.TEXT,
    placeholder: "Enter admission number",
    required: false,
  },
  {
    label: "Registration No",
    name: "regdNo",
    type: EInputType.TEXT,
    placeholder: "Enter registration number",
    required: false,
  },
  {
    label: "Academic Year",
    name: "academicYear",
    type: EInputType.TEXT,
    placeholder: "Enter academic year",
    required: false,
  },
  {
    label: "Joining Date",
    name: "joiningDate",
    type: EInputType.DATE,
    placeholder: "YYYY-MM-DD",
    required: false,
  },
  {
    label: "Expected Passout Date",
    name: "expectedPassoutDate",
    type: EInputType.DATE,
    placeholder: "YYYY-MM-DD",
    required: false,
  },
  {
    label: "Student Type",
    name: "studentType",
    type: EInputType.TEXT,
    placeholder: "Enter student type",
    required: false,
  },
  {
    label: "Roll No",
    name: "rollNo",
    type: EInputType.TEXT,
    placeholder: "Enter roll number",
    required: false,
  },
  {
    label: "Library ID",
    name: "libraryId",
    type: EInputType.TEXT,
    placeholder: "Enter library ID",
    required: false,
  },
  {
    label: "PAN No",
    name: "panNo",
    type: EInputType.TEXT,
    placeholder: "Enter PAN number",
    required: false,
  },
  {
    label: "Staff ID",
    name: "staffId",
    type: EInputType.TEXT,
    placeholder: "Enter staff ID",
    required: false,
  },
  {
    label: "Staff Type",
    name: "staffType",
    type: EInputType.TEXT,
    placeholder: "Enter staff type",
    required: false,
  },
  {
    label: "License No",
    name: "licenseNo",
    type: EInputType.TEXT,
    placeholder: "Enter license number",
    required: false,
  },
  {
    label: "Citizenship ID",
    name: "citizenshipId",
    type: EInputType.TEXT,
    placeholder: "Enter citizenship ID",
    required: false,
  },
  {
    label: "Designation",
    name: "designation",
    type: EInputType.TEXT,
    placeholder: "Enter designation",
    required: false,
  },
  {
    label: "Payroll Type",
    name: "payrollType",
    type: EInputType.TEXT,
    placeholder: "Enter payroll type",
    required: false,
  },
];
