import { EInputType, TFormSection } from "../types/formField";
import { z } from "zod";

export const registerFormSchema = z.object({
  name: z
    .string({ required_error: "enter your firstname" })
    .min(4, { message: "firstname should not be less than 4 words" }),
  email: z.string().email({ message: "please enter valid email" }),
  password: z
    .string()
    .min(8, { message: "password should not be less than 8 words" }),
  role: z.string(),
  dob: z.string().regex(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/),
  phone: z.string().regex(/^[0-9]{10}$/),
  paddress: z.string({ required_error: "enter your permanent address" }),
  taddress: z.string({ required_error: "enter your temporary address" }),
  bloodGroup: z.string(),
  religion: z.string(),
  gender: z.string(),
  motherTongue: z.string(),
  admissionNo: z.string(),
  regdNo: z.string(),
  academicYear: z.string(),
  joiningDate: z.string().regex(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/),
  expectedPassoutDate: z.string().regex(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/),
  studentType: z.string(),
  rollNo: z.string(),
  libraryId: z.string(),
  panNo: z.string(),
  staffId: z.string(),
  staffType: z.string(),
  licenseNo: z.string(),
  citizenshipId: z.string(),
  designation: z.string(),
  payrollType: z.string(),
});

export type TRegisterFormSchema = z.infer<typeof registerFormSchema>;
export const registerFormDefaultValue: Partial<TRegisterFormSchema> = {
  name: "",
  email: "",
  password: "",
  role: "",
  dob: "",
  phone: "",
  paddress: "",
  taddress: "",
  bloodGroup: "",
  religion: "",
  motherTongue: "",
  gender: "",
  admissionNo: "",
  regdNo: "",
  academicYear: "",
  joiningDate: "",
  expectedPassoutDate: "",
  studentType: "",
  rollNo: "",
  libraryId: "",
  panNo: "",
  staffId: "",
  staffType: "",
  licenseNo: "",
  citizenshipId: "",
  designation: "",
  payrollType: "",
};

export const registerFormField: TFormSection<TRegisterFormSchema>[] = [
  {
    title: "Personal Information",
    fields: [
      {
        label: "Name",
        name: "name",
        type: EInputType.TEXT,
        placeholder: "Enter your name",
        required: true,
        grid: 4,
      },
      {
        label: "Gender",
        name: "gender",
        type: EInputType.SELECT,
        placeholder: "Enter your gender",
        required: true,
        grid: 1,
        option: [
          { value: "MALE", label: "male" },
          { value: "FEMALE", label: "female" },
        ],
      },
      {
        label: "Email",
        name: "email",
        type: EInputType.EMAIL,
        placeholder: "Enter your email",
        required: true,
        grid: 2,
      },
      {
        label: "Password",
        name: "password",
        type: EInputType.PASSWORD,
        placeholder: "Enter your password",
        required: true,
        grid: 1,
      },
      {
        label: "Role",
        name: "role",
        type: EInputType.SELECT,
        placeholder: "Enter your role",
        required: true,
        grid: 1,
        option: [
          { value: "STUDENT", label: "Student" },
          { value: "PARENT", label: "guardian" },
        ],
      },
      {
        label: "Date of Birth",
        name: "dob",
        type: EInputType.DATE,
        placeholder: "YYYY-MM-DD",
        required: true,
        grid: 2,
      },
      {
        label: "Phone",
        name: "phone",
        type: EInputType.TEL,
        placeholder: "Enter your phone number",
        required: true,
        grid: 1,
      },
      {
        label: "Blood Group",
        name: "bloodGroup",
        type: EInputType.TEXT,
        placeholder: "Enter your blood group",
        required: false,
        grid: 1,
      },
      {
        label: "Religion",
        name: "religion",
        type: EInputType.TEXT,
        placeholder: "Enter your religion",
        required: false,
        grid: 2,
      },
      {
        label: "Mother Tongue",
        name: "motherTongue",
        type: EInputType.TEXT,
        placeholder: "Enter your mother tongue",
        required: false,
        grid: 1,
      },
      {
        label: "Permanent Address",
        name: "paddress",
        type: EInputType.TEXT,
        placeholder: "Enter your permanent address",
        required: true,
        grid: 2,
      },
      {
        label: "Temporary Address",
        name: "taddress",
        type: EInputType.TEXT,
        placeholder: "Enter your temporary address",
        required: true,
        grid: 2,
      },
    ],
  },
  {
    title: "Academic Information",
    fields: [
      {
        label: "Admission No",
        name: "admissionNo",
        type: EInputType.TEXT,
        placeholder: "Enter admission number",
        required: false,
        grid: 1,
      },
      {
        label: "Registration No",
        name: "regdNo",
        type: EInputType.TEXT,
        placeholder: "Enter registration number",
        required: false,
        grid: 1,
      },
      {
        label: "Academic Year",
        name: "academicYear",
        type: EInputType.DATE,
        placeholder: "Enter academic year",
        required: false,
        grid: 1,
      },
      {
        label: "Joining Date",
        name: "joiningDate",
        type: EInputType.DATE,
        placeholder: "YYYY-MM-DD",
        required: false,
        grid: 1,
      },
      {
        label: "Expected Passout Date",
        name: "expectedPassoutDate",
        type: EInputType.DATE,
        placeholder: "YYYY-MM-DD",
        required: false,
        grid: 1,
      },
      {
        label: "Student Type",
        name: "studentType",
        type: EInputType.TEXT,
        placeholder: "Enter student type",
        required: false,
        grid: 1,
      },
      {
        label: "Roll No",
        name: "rollNo",
        type: EInputType.TEXT,
        placeholder: "Enter roll number",
        required: false,
        grid: 1,
      },
      {
        label: "Library ID",
        name: "libraryId",
        type: EInputType.TEXT,
        placeholder: "Enter library ID",
        required: false,
        grid: 1,
      },
      {
        label: "PAN No",
        name: "panNo",
        type: EInputType.TEXT,
        placeholder: "Enter PAN number",
        required: false,
        grid: 1,
      },
      {
        label: "Staff ID",
        name: "staffId",
        type: EInputType.TEXT,
        placeholder: "Enter staff ID",
        required: false,
        grid: 1,
      },
      {
        label: "Staff Type",
        name: "staffType",
        type: EInputType.TEXT,
        placeholder: "Enter staff type",
        required: false,
        grid: 1,
      },
      {
        label: "License No",
        name: "licenseNo",
        type: EInputType.TEXT,
        placeholder: "Enter license number",
        required: false,
        grid: 1,
      },
      {
        label: "Citizenship ID",
        name: "citizenshipId",
        type: EInputType.TEXT,
        placeholder: "Enter citizenship ID",
        required: false,
        grid: 1,
      },
      {
        label: "Designation",
        name: "designation",
        type: EInputType.TEXT,
        placeholder: "Enter designation",
        required: false,
        grid: 1,
      },
      {
        label: "Payroll Type",
        name: "payrollType",
        type: EInputType.TEXT,
        placeholder: "Enter payroll type",
        required: false,
        grid: 1,
      },
    ],
  },
];
